/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 25-mar-2017 00:07:25 				*/
/*  DBMS       : SQL Server 2005 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cliente_Cidade]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Cliente_Cidade]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Concessionaria_Cidade]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Concessionaria] DROP CONSTRAINT [FK_Concessionaria_Cidade]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pecaconcessionaria_Concessionaria]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pecaconcessionaria] DROP CONSTRAINT [FK_Pecaconcessionaria_Concessionaria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pecaconcessionaria_Peca]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pecaconcessionaria] DROP CONSTRAINT [FK_Pecaconcessionaria_Peca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pecarequisicao_Peca]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pecarequisicao] DROP CONSTRAINT [FK_Pecarequisicao_Peca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pecarequisicao_Requisicao]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pecarequisicao] DROP CONSTRAINT [FK_Pecarequisicao_Requisicao]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Requisicao_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Requisicao] DROP CONSTRAINT [FK_Requisicao_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Requisicao_Usuarios]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Requisicao] DROP CONSTRAINT [FK_Requisicao_Usuarios]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cidade]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cidade]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Concessionaria]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Concessionaria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Peca]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Peca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pecaconcessionaria]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pecaconcessionaria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pecarequisicao]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pecarequisicao]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Requisicao]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Requisicao]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuarios]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuarios]
GO

/* Create Tables */

CREATE TABLE [Cidade]
(
	[CidadeID] Integer NOT NULL,
	[Nome] varchar(50) NULL,
	[Estado] int NULL
)
GO

alter table cliente
drop column [DataNascimento]
alter table Cliente add [Telefone] varchar(20) NULL;

CREATE TABLE [Cliente]
(
	[ClienteID] Integer NOT NULL,
	[CidadeID] int NULL,
	[Nome] varchar(50) NULL,
	[Sexo] int NULL,
	[Rg] int NULL,
	[Cpf] varchar(20) NULL,
	[Endereco] varchar(50) NULL,
	[Numero] int NULL,
	[Complemento] varchar(50) NULL,
	[Bairro] varchar(50) NULL,
	[Cep] varchar(20) NULL,
	[Cnpj] varchar(20) NULL,
	[Inscricaomunicipal] varchar(15) NULL,
	[Email] varchar(50) NULL,
	[Telefone] varchar(20) NULL,
	[TipoPessoa] int NOT NULL
)
GO

CREATE TABLE [Concessionaria]
(
	[ConcessionariaID] Integer NOT NULL,
	[CidadeID] int NULL,
	[Nome] varchar(50) NULL,
	[Cnpj] varchar(15) NULL,
	[Dn] int NULL,
	[Endereco] varchar(50) NULL,
	[Telefone] varchar(50) NULL,
)
GO

CREATE TABLE [Peca]
(
	[PecaID] Integer NOT NULL,
	[Referencia] varchar(50) NULL,
	[Descricao] varchar(50) NULL,
	[Valor] decimal(10,2) NULL,
)
GO

CREATE TABLE [Pecaconcessionaria]
(
	[PecaconcessionariaID] Integer NOT NULL,
	[ConcessionariaID] int NULL,
	[PecaID] int NULL,
	[Quantidade] int NULL,
	[Tempotransporte] int NULL,
	[Tipotransporte] varchar(50) NULL,
	[Transportadora] varchar(50) NULL
)
GO

alter table [Pecarequisicao] add [Valor] varchar(20) NULL;
CREATE TABLE [Pecarequisicao]
(
	[Quantpeca] int NULL,
	[PecarequisicaoID] Integer NOT NULL,
	[PecaID] int NOT NULL,
	[RequisicaoID] int NOT NULL,
	[Valor] varchar(20) NULL
)
GO

alter table [Requisicao]
drop column [Datarequisicao]
alter table [Requisicao] add [Datarequisicao] varchar(20) NULL;

CREATE TABLE [Requisicao]
(
	[RequisicaoID] Integer NOT NULL,
	[ClienteID] int NULL,
	[UsuariosID] int NULL,
	[Numerorequisicao] int NULL,
	[Datapedido] varchar(20) NULL,
	[Datarequisicao] varchar(20) NULL,
	[Estado] int NULL,
	[Finalidade] varchar(50) NULL,
)
GO

CREATE TABLE [Usuarios]
(
	[UsuariosID] Integer NOT NULL,
	[Nome] varchar(20) NULL,
	[Login] varchar(20) NULL,
	[Senha] int NULL,
	[Email] varchar(50) NULL,
	[Responsavel] int NULL,
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cidade] 
 ADD CONSTRAINT [PK_Cidade]
	PRIMARY KEY CLUSTERED ([CidadeID] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([ClienteID] ASC)
GO

ALTER TABLE [Concessionaria] 
 ADD CONSTRAINT [PK_Concessionaria]
	PRIMARY KEY CLUSTERED ([ConcessionariaID] ASC)
GO

ALTER TABLE [Peca] 
 ADD CONSTRAINT [PK_Peca]
	PRIMARY KEY CLUSTERED ([PecaID] ASC)
GO

ALTER TABLE [Pecaconcessionaria] 
 ADD CONSTRAINT [PK_Pecaconcessionaria]
	PRIMARY KEY CLUSTERED ([PecaconcessionariaID] ASC)
GO

ALTER TABLE [Pecarequisicao] 
 ADD CONSTRAINT [PK_Pecarequisicao]
	PRIMARY KEY CLUSTERED ([PecarequisicaoID] ASC)
GO

ALTER TABLE [Requisicao] 
 ADD CONSTRAINT [PK_Requisicao]
	PRIMARY KEY CLUSTERED ([RequisicaoID] ASC)
GO

ALTER TABLE [Usuarios] 
 ADD CONSTRAINT [PK_Usuarios]
	PRIMARY KEY CLUSTERED ([UsuariosID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Cliente_Cidade]
	FOREIGN KEY ([CidadeID]) REFERENCES [Cidade] ([CidadeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Concessionaria] ADD CONSTRAINT [FK_Concessionaria_Cidade]
	FOREIGN KEY ([CidadeID]) REFERENCES [Cidade] ([CidadeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pecaconcessionaria] ADD CONSTRAINT [FK_Pecaconcessionaria_Concessionaria]
	FOREIGN KEY ([ConcessionariaID]) REFERENCES [Concessionaria] ([ConcessionariaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pecaconcessionaria] ADD CONSTRAINT [FK_Pecaconcessionaria_Peca]
	FOREIGN KEY ([PecaID]) REFERENCES [Peca] ([PecaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pecarequisicao] ADD CONSTRAINT [FK_Pecarequisicao_Peca]
	FOREIGN KEY ([PecaID]) REFERENCES [Peca] ([PecaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pecarequisicao] ADD CONSTRAINT [FK_Pecarequisicao_Requisicao]
	FOREIGN KEY ([RequisicaoID]) REFERENCES [Requisicao] ([RequisicaoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Requisicao] ADD CONSTRAINT [FK_Requisicao_Cliente]
	FOREIGN KEY ([ClienteID]) REFERENCES [Cliente] ([ClienteID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Requisicao] ADD CONSTRAINT [FK_Requisicao_Usuarios]
	FOREIGN KEY ([UsuariosID]) REFERENCES [Usuarios] ([UsuariosID]) ON DELETE No Action ON UPDATE No Action
GO




INSERT INTO Peca (descricao,Referencia,Valor) values('Fitro de oleo','EM5G/6714/AA/',56);

UPDATE Peca SET Descricao = 'Fitro de oleo', Referencia = 'EM5G/6714/AA/', Valor= 56 where pecaId= 2;

SELECT * FROM Cliente where TipoPessoa = 1

Select * from Cidade

INSERT into Cidade ([cidadeId], [nome], [estado]) VALUES (1, N'ABADIA', 5)

update Cliente set Sexo = null  where ClienteId = 2

update Requisicao set Datarequisicao = '12/05/2017' where RequisicaoID = 2


Select * from Usuarios

Delete from cliente

insert into Cliente (CidadeID,Nome,Sexo,Rg,Endereco,Numero,Complemento,Bairro,Inscricaomunicipal,Email,TipoPessoa,Cpf,Cep,Cnpj,Telefone) 
values (1,'Mega Veiculos',null,null,'Rua da beira',6730,null,'El dorado','121333131','igor@megaveiculos.com',2,null,'76808238','03376298000127','32277700');

select * from Pecarequisicao



insert into Pecarequisicao ([PecaID],[Quantpeca],[RequisicaoID],[Valor]) values (1,2,2,100);

insert into Requisicao ([ClienteID],[UsuariosID],[Numerorequisicao],[Datapedido],[Datarequisicao],[Estado],[Finalidade]) values (1015,1,1234,'01/05/2017','12/05/2017',2,'atender cliente balcao');