///////////////////////////////////////////////////////////
//  Estado.cs
//  Implementation of the Class Estado
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:10
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
	public enum Estado {

		acre = 1,
		alagoas = 2 ,
		amapa = 3,
		amazonas = 4,
		bahia = 5,
		ceara = 6,
		brasilia = 7,
		espiritoSanto = 8,
		goias = 9,
		maranhao = 10,
		matoGrosso = 11,
		matoGrossoSul = 12,
		minasGerais = 13,
		para = 14,
		paraiba = 15,
		parana = 16,
		pernambuco = 17,
		piaui = 18,
		rioDeJaneiro = 19,
		rioGrandeNorte = 20,
		rioGrandeSul = 21,
		rondonia = 22,
		roraima = 23,
		santaCatarina = 24,
		saoPaulo = 25,
		sergipe = 26,
		tocantins = 27

	}//end Estado

}//end namespace Model