///////////////////////////////////////////////////////////
//  Peca.cs
//  Implementation of the Class Peca
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:10
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
	public class Peca {

        public string Descricao { get; set; }
        public bool PecaB { get; set; }
        public int PecaId { get; set; }
        public string Referencia { get; set; }
        public decimal Valor { get; set; }
        public IList<PecaConcessionaria> ListaDePecaConcessionaria { get; set; }

        
    }//end Peca

}//end namespace Model