///////////////////////////////////////////////////////////
//  Peca.cs
//  Implementation of the Class Peca
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:10
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using SisDec.Repository;

namespace SisDec.Models
{
	public class Peca {

        [Required (ErrorMessage = "O campo Descrição deve ser preenchido!")]
        [StringLength(30, MinimumLength = 10, ErrorMessage = "Nome deve ter entre 10 e 30 caracteres!")]
        public string Descricao { get; set; }

        public int PecaId { get; set; }

        [Required (ErrorMessage = "O campo Referencia deve ser preenchido!")]
        public string Referencia { get; set; }

        [Required(ErrorMessage = "O campo Valor deve ser preenchido!")]
        public decimal Valor { get; set; }

        public int Quantidade { get; set; }

        public IList<PecaConcessionaria> ListaDePecaConcessionaria { get; set; }

        public IList<Peca> BuscarTodos()
        {
            return new RepositoryPeca().BuscarTodos();
        }

        public void Gravar ()
        {
            RepositoryPeca repositoryPeca = new RepositoryPeca();
            if (PecaId == 0)
            {
                repositoryPeca.Inserir(this);
            }
            else
            {
                repositoryPeca.Update(this);
            }
            
        }

        
    }//end Peca

}//end namespace Model