///////////////////////////////////////////////////////////
//  PecaConcessionaria.cs
//  Implementation of the Class PecaConcessionaria
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:10
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
	public class PecaConcessionaria {

        public int Quantidade { get; set; }
        public int TempoTransporte { get; set; }
        public string TipoTransporte { get; set; }
        public decimal ValorUnitario { get; set; }
        public Cidade objPeca { get; set; }

        
    }//end PecaConcessionaria

}//end namespace Model