///////////////////////////////////////////////////////////
//  Pessoa.cs
//  Implementation of the Class Pessoa
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:10
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
    public abstract class Pessoa
    {

        public string Bairro { get; set; }
        public decimal Cep { get; set; }
        public string Cidade { get; set; }
        public string Complemento { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public int Numero { get; set; }
        public decimal Rendimento { get; set; }
        public string Sexo { get; set; }
        public decimal Telefone { get; set; }




    }//end Pessoa

}//end namespace Model