///////////////////////////////////////////////////////////
//  Pessoa.cs
//  Implementation of the Class Pessoa
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:10
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
    public abstract class Pessoa
    {
        
        public string Bairro { get; set; }
        public decimal Cep { get; set; }
        public string Complemento { get; set; }
        [Display(Name = "Data de Nascimento"), DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime DataNascimento { get; set; }
        [RegularExpression(@"^ ([\w\.\-] +)@([\w\-] +)((\.(\w){2, 3})+)$", ErrorMessage="O e-mail não é válido.")]
        public string Email { get; set; }
        public string Endereco { get; set; }
        public int Numero { get; set; }
        public decimal Rendimento { get; set; }
        public string Sexo { get; set; }
        public decimal Telefone { get; set; }

        public Cidade objCidade { get; set; }


        public Pessoa()
        {
            objCidade = new Cidade();
        }

    }//end Pessoa

}//end namespace Model