///////////////////////////////////////////////////////////
//  Reponsavel.cs
//  Implementation of the Class Reponsavel
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:11
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
	public enum Reponsavel : int {

        [Display(Name = "Gerente Oficina")]
        gerenteOficina = 1,
        [Display(Name = "Gerente Funilaria")]
        gerenteFunilaria = 2,
        [Display(Name = "Secretária")]
        secretaria = 3,
        [Display(Name = "Vendedor")]
        vendedor = 4,
        [Display(Name = "Consultor")]
        consultor = 5

	}//end Reponsavel

}//end namespace Model