///////////////////////////////////////////////////////////
//  Reponsavel.cs
//  Implementation of the Class Reponsavel
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:11
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
	public enum Reponsavel : int {

		gerenteOficina = 1,
		gerenteFunilaria = 2,
		secretaria = 3,
		vendedor = 4

	}//end Reponsavel

}//end namespace Model