///////////////////////////////////////////////////////////
//  Requisicao.cs
//  Implementation of the Class Requisicao
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:11
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
	public class Requisicao {

        [Display(Name = "Numero da Requisição")]
        public int NumeroRequisicao { get; set; }
        [Display(Name = "Data do Pedido")]
        public DateTime DataPedido { get; set; }

        public DateTime DataRequisicao { get; set; }
        public string Finalidade { get; set; }
        //public int Estado { get; set; }

        public List<PecaRequisicao> ListaPecaRequisicao { get; set; }
        public Cliente ObjCliente { get; set; }
        public Peca objPeca { get; set; }

    }//end Requisicao

}//end namespace Model