///////////////////////////////////////////////////////////
//  Usuarios.cs
//  Implementation of the Class Usuarios
//  Generated by Enterprise Architect
//  Created on:      24-fev-2017 23:25:11
//  Original author: soare
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SisDec.Models
{
    public class Usuarios : Pessoa
    {
        public string Login { get; set; }
        public int Senha { get; set; }

       
    }//end Usuarios

}//end namespace Model